export const SHOW_SPECIFICATIONS = "SHOW_SPECIFICATIONS";

export const RELOAD_MODULE = "RELOAD_MODULE";

export const SHOW_SHAREMODULE = "SHOW_SHAREMODULE ";

export const SHOW_CONTACTMODULE = "SHOW_CONTACTMODULE";
